export default [
  {
    id: '1',
    menuParentId: '-1',
    icon: '/icons/dashboard.svg',
    name: '仪表盘',
    route: '/dashboard',
  },
  {
    id: '2',
    breadcrumbParentId: '1',
    name: '安全总览',
    icon: '/icons/dashboard.svg',
    route: '/dashboard',
  },
  // {
  //   id: '21',
  //   menuParentId: '-1',
  //   breadcrumbParentId: '2',
  //   name: '用户详情',
  //   route: '/user/:id',
  // },
  {
    id: '3',
    breadcrumbParentId: '1',
    name: '事件日志',
    icon: '/icons/event.svg',
    route: '/event',
  },
  {
    id: '4',
    breadcrumbParentId: '1',
    name: '全屏监控',
    icon: '/icons/situation.svg',
    route: '/situation',
  },
  {
    id: '8',
    breadcrumbParentId: '1',
    name: '资产管理',
    icon: '/icons/assets.svg',
    route: '/assets',
  },
  {
    id: '81',
    menuParentId: '8',
    breadcrumbParentId: '2',
    name: '资产发现',
    route: '/assets/discover',
  },
  {
    id: '82',
    menuParentId: '8',
    breadcrumbParentId: '2',
    name: '资产备案',
    route: '/assets/case',
  },
  {
    id: '83',
    menuParentId: '8',
    breadcrumbParentId: '2',
    name: '资产分组',
    route: '/assets/group',
  },
  {
    id: '9',
    breadcrumbParentId: '1',
    name: '漏洞管理',
    icon: '/icons/loophole.svg',
    route: '/loophole',
  },
  {
    id: '91',
    menuParentId: '9',
    breadcrumbParentId: '1',
    name: '漏洞检测',
    route: '/loophole/check',
  },
  {
    id: '92',
    menuParentId: '9',
    breadcrumbParentId: '1',
    name: '报表输出',
    route: '/loophole/report',
  },
  {
    id: '10',
    breadcrumbParentId: '1',
    name: '威胁防护',
    icon: '/icons/protect.svg',
    route: '/protect',
  },
  {
    id: '101',
    menuParentId: '10',
    breadcrumbParentId: '1',
    name: '阻断管理',
    route: '/protect/blocking',
  },
  {
    id: '102',
    menuParentId: '10',
    breadcrumbParentId: '1',
    name: 'IP阻断',
    route: '/protect/ip',
  },
  {
    id: '6',
    breadcrumbParentId: '1',
    name: '统计报表',
    icon: '/icons/report.svg',
    route: '/report',
  },
  {
    id: '5',
    breadcrumbParentId: '1',
    name: '规则策略',
    icon: '/icons/tactic.svg',
    route: '/tactic',
  },
  {
    id: '51',
    menuParentId: '5',
    breadcrumbParentId: '1',
    name: '用户规则',
    route: '/tactic/user',
  },
  {
    id: '52',
    menuParentId: '5',
    breadcrumbParentId: '1',
    name: '系统规则',
    route: '/tactic/system',
  },
  {
    id: '53',
    menuParentId: '5',
    breadcrumbParentId: '1',
    name: '白名单',
    route: '/tactic/whitelist',
  },
  {
    id: '7',
    breadcrumbParentId: '1',
    name: '配置管理',
    icon: '/icons/system.svg',
    route: '/system',
  },
  {
    id: '71',
    menuParentId: '7',
    breadcrumbParentId: '2',
    name: '用户管理',
    route: '/system/user',
  },
  {
    id: '72',
    menuParentId: '7',
    breadcrumbParentId: '2',
    name: '告警管理',
    route: '/system/warn',
  },
  {
    id: '73',
    menuParentId: '7',
    breadcrumbParentId: '2',
    name: '网络管理',
    route: '/system/network',
  },
  {
    id: '74',
    menuParentId: '7',
    breadcrumbParentId: '2',
    name: '系统状态',
    route: '/system/status',
  },
]
